<Managment>:
    Menu:
        name: 'menu'
    Tasks:
        name: 'tarefas'

<Menu>:
    BoxLayout:
        orientation: 'vertical'
        padding:100
        spacing: 30
        Image:
            source: 'imagens/user1.jpg'
            size_hint_y: None
            height: 200
        Button: 
            text: 'Tarefas'
            on_release: app.root.current = 'tarefas'

        Button: 
            text: 'Assistente Virtual'

        Button: 
            text: 'Sair'
            on_release: app.stop()

<Tasks>: 
    BoxLayout:
        orientation: 'vertical'
        ActionBar:
            ActionView:
                ActionPrevious:
                    title: 'Tasks'
                    on_release: app.root.current = 'menu'

                ActionButton:
                    text: 'Sair'
                    on_release: app.stop()

                ActionSeparator:

        ScrollView:
            BoxLayout:     
                id: box
                orientation: 'vertical'
                size_hint_y: None
                height: self.minimum_height
        BoxLayout:
            size_hint_y: None
            height: 60
            TextInput:
                id: texto           
            Button:
                text: '+'
                size_hint_x: None
                width: 60
                on_release: root.addWidget()

<Task>
    size_hint_y: None
    height: 200
    Label:
        id: label
        font_size: 30
    Button:
        text: 'x'
        size_hint_x:None
        width: 60
        on_release: app.root.get_screen('tarefas').ids.box.remove_widget(self.parent)
